[package]
exclude = [
	"src",
	".git",
	"tests",
	"node_modules",
	".codecov.yml",
	"composer.json",
	"composer.lock",
	"_config.yml",
	".drone.yml",
	".travis.yml",
	".eslintignore",
	".eslintrc.yml",
	".github",
	".gitignore",
	"issue_template.md",
	"krankerl.toml",
	"Makefile",
	"mkdocs.yml",
	"package.json",
	"package-lock.json",
	"README.md",
	"run-eslint.sh",
	"webpack.*",
	"img/screenshots",
	"utilities",
]

before_cmds = [
	"npm install",
	"npm run build"
]
